version: '3.8'
services:
  redis:
    image: redis:latest
    networks:
      - backend_network
  postgres:
    image: postgres:latest
    env_file:
      - postgres.env
    networks:
      - backend_network
  api:
    build: ./backend
    command: node index.js
    networks:
      - backend_network
    depends_on:
      - redis
      - postgres
    restart: always
  proxy:
    image: nginx:latest
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - backend_network
    ports:
      - '80:80'
    depends_on:
      - api

networks:
  backend_network:
    external: false
    name: backend_network
